#!/bin/bash

sxhkd &
picom &
nitrogen --restore &
~/.config/.scripts/launch_polybar.sh &
~/.config/.scripts/launch_redshift.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

# Set border colors and width
bspc config normal_border_color     "#2e3440"
bspc config active_border_color     "#d8dee9"
bspc config focused_border_color    "#d8dee9"
bspc config border_width            1

# Set windows
bspc config window_gap          12
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Set rules
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Pavucontrol state=floating
bspc rule -a Screenkey manage=off
